version: '3.9'

services:
  # the order of the containers doesn't really matter

  postgres:   #container 1  # dependant on container mongodb
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-single  #container name HAS! to be unique when they are inside the same solution
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes: #mount (Also refered as map) a specific directory
        - ./data/order:/var/lib/postgresql/data-d
        - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:   #container 1  # dependant on container mongodb
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-single  #container name HAS! to be unique when they are inside the same solution
    environment:
        - PGADMIN_DEFAULT_EMAIL=user@domain.ca
        - PGADMIN_DEFAULT_PASSWORD=password




