version: '3.9'

services:
  # the order of the containers doesn't really matter

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev","--import-realm"]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      ROOT_LOGLEVEL: DEBUG
      JBOSS_LOG_MANAGER_ROOT_LOGGER: DEBUG, stdout, FILE
    ports:
      - "8089:8080"

  postgres-keycloak:   #container 1  # dependant on container mongodb
    image: postgres
    ports:
      - "5430:5432"
    container_name: postgres-single  #container name HAS! to be unique when they are inside the same solution
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
    volumes: #mount (Also refered as map) a specific directory
        - ./data/postgres/keycloak:/var/lib/postgresql/data
    networks:
      - spring

 # pgadmin:   #container 1  # dependant on container mongodb
 #   image: dpage/pgadmin4
 #   ports:
 #     - "8888:80"
 #   container_name: pgadmin-single  #container name HAS! to be unique when they are inside the same solution
 #   environment:
 #       - PGADMIN_DEFAULT_EMAIL=user@domain.ca
 #       - PGADMIN_DEFAULT_PASSWORD=password
 #   networks:
 #     -spring

networks:
  spring:
    driver: bridge




